---
- name: Enable epel-release
  yum:
    name: epel-release
    state: present

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest
    update_cache: yes
  when: update_all_packages|bool

- name: Install common packages
  yum:
    name: "{{ common_packages }}"
    state: present
