---
- name: Download Kubernetes container images
  shell: kubeadm config images pull
  when: inventory_hostname in groups["k8s_masters"]

- name: Initializing first control plane node
  include_tasks: init_first_master.yml
  when: inventory_hostname == groups["k8s_masters"][0]

- name: Initializing other control plane nodes
  include_tasks: init_other_masters.yml
  when: inventory_hostname != groups["k8s_masters"][0] and inventory_hostname in groups["k8s_masters"]
