---
- name: Create Kubernetes namespace kube-monitoring
  k8s:
    name: kube-monitoring
    api_version: v1
    kind: Namespace
    state: present

- name: Create metrics-server chart value
  template:
    src: metrics-server-values.yml.j2
    dest: /tmp/metrics-server-values.yml

- name: Install metrics-server chart
  shell: helm upgrade --install metrics-server stable/metrics-server --namespace kube-monitoring -f /tmp/metrics-server-values.yml

