---
- name: Create Kubernetes namespace kube-monitoring
  k8s:
    name: kube-monitoring
    api_version: v1
    kind: Namespace
    state: present

- name: Create Helm values directory
  file:
    path: "{{ helm_values_directory }}"
    state: directory
    mode: "0755"
  when: inventory_hostname == groups["k8s_masters"][0]

- name: Create metrics-server chart value
  template:
    src: metrics-server-values.yml.j2
    dest: "{{ helm_values_directory }}/metrics-server-values.yml"

- name: Install metrics-server chart
  shell: helm upgrade --install metrics-server stable/metrics-server --namespace kube-monitoring -f "{{ helm_values_directory }}/metrics-server-values.yml"
