---
- name: Generate join token
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['k8s_masters'][0] }}"

- set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

- debug: var=kubeadm_join

- name: Run kubeadm join
  shell: "{{ kubeadm_join }} --ignore-preflight-errors=swap"

- name: Set kubernetes worker role on worker node
  shell: kubectl label node {{ inventory_hostname }}  node-role.kubernetes.io/worker=
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['k8s_masters'][0] }}"

