---
- name: Create Kubernetes namespace kube-monitoring
  k8s:
    name: kube-monitoring
    api_version: v1
    kind: Namespace
    state: present

- name: Create prometheus-operator chart value
  template:
    src: prometheus-operator-values.yml.j2
    dest: /tmp/prometheus-operator-values.yml

- name: Install prometheus-operator chart
  shell: helm upgrade --install prometheus-operator stable/prometheus-operator --namespace kube-monitoring --values /tmp/prometheus-operator-values.yml

